# i believe this general.import = [] syntax is for newer alacritty, if it doesn't work, update your alacritty
general.import = [
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Fix padding around neovim
[font.offset]
x = 0
y = 0

[window]
decorations = "Full"
dynamic_padding = true

[window.padding]
x = 4
y = 4

[env]
TERM = "xterm-256color"
